[2025-01-22T11:02:30.088+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T11:02:30.096+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-debug manual__2025-01-22T10:59:47.101605+00:00 [queued]>
[2025-01-22T11:02:30.102+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-debug manual__2025-01-22T10:59:47.101605+00:00 [queued]>
[2025-01-22T11:02:30.103+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T11:02:30.126+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-22 10:59:47.101605+00:00
[2025-01-22T11:02:30.130+0000] {standard_task_runner.py:72} INFO - Started process 70156 to run task
[2025-01-22T11:02:30.133+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake', 'dbt_tasks.dbt-debug', 'manual__2025-01-22T10:59:47.101605+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpy297vnwp']
[2025-01-22T11:02:30.135+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask dbt_tasks.dbt-debug
[2025-01-22T11:02:30.190+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake.dbt_tasks.dbt-debug manual__2025-01-22T10:59:47.101605+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T11:02:30.277+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T10:59:47.101605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T10:59:47.101605+00:00'
[2025-01-22T11:02:30.279+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T11:02:30.280+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T11:02:30.281+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 11:02:30.098311+00:00
[2025-01-22T11:02:30.282+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake and current dag run status:running
[2025-01-22T11:02:30.283+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T11:02:30.286+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T11:02:30.287+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T11:02:30.293+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T11:02:41.763+0000] {subprocess.py:106} INFO - [0m11:02:41  Running with dbt=1.9.1
[2025-01-22T11:02:41.962+0000] {subprocess.py:106} INFO - [0m11:02:41  dbt version: 1.9.1
[2025-01-22T11:02:41.963+0000] {subprocess.py:106} INFO - [0m11:02:41  python version: 3.12.3
[2025-01-22T11:02:41.964+0000] {subprocess.py:106} INFO - [0m11:02:41  python path: /mnt/c/Users/psara/shrovandbtairflow/airflow_venv/bin/python3
[2025-01-22T11:02:41.965+0000] {subprocess.py:106} INFO - [0m11:02:41  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
[2025-01-22T11:02:44.590+0000] {subprocess.py:106} INFO - [0m11:02:44  Using profiles dir at /mnt/c/Users/psara/.dbt
[2025-01-22T11:02:44.592+0000] {subprocess.py:106} INFO - [0m11:02:44  Using profiles.yml file at /mnt/c/Users/psara/.dbt/profiles.yml
[2025-01-22T11:02:44.594+0000] {subprocess.py:106} INFO - [0m11:02:44  Using dbt_project.yml file at /mnt/c/Users/psara/shrovandbtsnowflake/dbt_project.yml
[2025-01-22T11:02:44.607+0000] {subprocess.py:106} INFO - [0m11:02:44  adapter type: snowflake
[2025-01-22T11:02:44.608+0000] {subprocess.py:106} INFO - [0m11:02:44  adapter version: 1.9.0
[2025-01-22T11:02:44.741+0000] {subprocess.py:106} INFO - [0m11:02:44  Configuration:
[2025-01-22T11:02:44.743+0000] {subprocess.py:106} INFO - [0m11:02:44    profiles.yml file [[32mOK found and valid[0m]
[2025-01-22T11:02:44.745+0000] {subprocess.py:106} INFO - [0m11:02:44    dbt_project.yml file [[32mOK found and valid[0m]
[2025-01-22T11:02:44.746+0000] {subprocess.py:106} INFO - [0m11:02:44  Required dependencies:
[2025-01-22T11:02:44.754+0000] {subprocess.py:106} INFO - [0m11:02:44   - git [[32mOK found[0m]
[2025-01-22T11:02:44.756+0000] {subprocess.py:106} INFO - 
[2025-01-22T11:02:44.757+0000] {subprocess.py:106} INFO - [0m11:02:44  Connection:
[2025-01-22T11:02:44.758+0000] {subprocess.py:106} INFO - [0m11:02:44    account: PUBFORT-NI17152
[2025-01-22T11:02:44.759+0000] {subprocess.py:106} INFO - [0m11:02:44    user: shrovan
[2025-01-22T11:02:44.760+0000] {subprocess.py:106} INFO - [0m11:02:44    database: YEAR2025
[2025-01-22T11:02:44.761+0000] {subprocess.py:106} INFO - [0m11:02:44    warehouse: COMPUTE_WH
[2025-01-22T11:02:44.762+0000] {subprocess.py:106} INFO - [0m11:02:44    role: ACCOUNTADMIN
[2025-01-22T11:02:44.763+0000] {subprocess.py:106} INFO - [0m11:02:44    schema: JAN
[2025-01-22T11:02:44.764+0000] {subprocess.py:106} INFO - [0m11:02:44    authenticator: None
[2025-01-22T11:02:44.765+0000] {subprocess.py:106} INFO - [0m11:02:44    oauth_client_id: None
[2025-01-22T11:02:44.766+0000] {subprocess.py:106} INFO - [0m11:02:44    query_tag: None
[2025-01-22T11:02:44.767+0000] {subprocess.py:106} INFO - [0m11:02:44    client_session_keep_alive: False
[2025-01-22T11:02:44.769+0000] {subprocess.py:106} INFO - [0m11:02:44    host: None
[2025-01-22T11:02:44.770+0000] {subprocess.py:106} INFO - [0m11:02:44    port: None
[2025-01-22T11:02:44.771+0000] {subprocess.py:106} INFO - [0m11:02:44    proxy_host: None
[2025-01-22T11:02:44.771+0000] {subprocess.py:106} INFO - [0m11:02:44    proxy_port: None
[2025-01-22T11:02:44.772+0000] {subprocess.py:106} INFO - [0m11:02:44    protocol: None
[2025-01-22T11:02:44.773+0000] {subprocess.py:106} INFO - [0m11:02:44    connect_retries: 1
[2025-01-22T11:02:44.775+0000] {subprocess.py:106} INFO - [0m11:02:44    connect_timeout: None
[2025-01-22T11:02:44.776+0000] {subprocess.py:106} INFO - [0m11:02:44    retry_on_database_errors: False
[2025-01-22T11:02:44.777+0000] {subprocess.py:106} INFO - [0m11:02:44    retry_all: False
[2025-01-22T11:02:44.777+0000] {subprocess.py:106} INFO - [0m11:02:44    insecure_mode: False
[2025-01-22T11:02:44.779+0000] {subprocess.py:106} INFO - [0m11:02:44    reuse_connections: True
[2025-01-22T11:02:44.781+0000] {subprocess.py:106} INFO - [0m11:02:44  Registered adapter: snowflake=1.9.0
[2025-01-22T11:02:57.487+0000] {subprocess.py:106} INFO - [0m11:02:57    Connection test: [[32mOK connection ok[0m]
[2025-01-22T11:02:57.492+0000] {subprocess.py:106} INFO - 
[2025-01-22T11:02:57.498+0000] {subprocess.py:106} INFO - [0m11:02:57  [32mAll checks passed![0m
[2025-01-22T11:02:59.316+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-22T11:02:59.350+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T11:02:59.351+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=airflow_dbt_snowflake, task_id=dbt_tasks.dbt-debug, run_id=manual__2025-01-22T10:59:47.101605+00:00, execution_date=20250122T105947, start_date=20250122T110230, end_date=20250122T110259
[2025-01-22T11:02:59.390+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-22T11:02:59.392+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-22T11:02:59.393+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake queued_at:2025-01-22 10:59:47.196650+00:00
[2025-01-22T11:02:59.394+0000] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-3U4JI4R2. operator:BashOperator
[2025-01-22T11:03:00.369+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T11:03:00.387+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T11:03:00.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
