[2025-01-22T13:03:03.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T13:03:03.258+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T13:03:03.264+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T13:03:03.265+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-01-22T13:03:03.296+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-21 00:00:00+00:00
[2025-01-22T13:03:03.300+0000] {standard_task_runner.py:72} INFO - Started process 101830 to run task
[2025-01-22T13:03:03.302+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake1', 'dbt_tasks.dbt-debug', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmp9lve2pv0']
[2025-01-22T13:03:03.305+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask dbt_tasks.dbt-debug
[2025-01-22T13:03:03.368+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake1.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T13:03:03.464+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake1' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T13:03:03.467+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T13:03:03.469+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T13:03:03.470+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 13:03:03.259968+00:00
[2025-01-22T13:03:03.471+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake1 and current dag run status:running
[2025-01-22T13:03:03.472+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T13:03:03.475+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-22T13:03:03.477+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T13:03:03.485+0000] {subprocess.py:99} INFO - Output:
[2025-01-22T13:03:15.413+0000] {subprocess.py:106} INFO - [0m13:03:15  Running with dbt=1.9.1
[2025-01-22T13:03:15.658+0000] {subprocess.py:106} INFO - [0m13:03:15  dbt version: 1.9.1
[2025-01-22T13:03:15.659+0000] {subprocess.py:106} INFO - [0m13:03:15  python version: 3.12.3
[2025-01-22T13:03:15.660+0000] {subprocess.py:106} INFO - [0m13:03:15  python path: /mnt/c/Users/psara/shrovandbtairflow/airflow_venv/bin/python3
[2025-01-22T13:03:15.662+0000] {subprocess.py:106} INFO - [0m13:03:15  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
[2025-01-22T13:03:18.443+0000] {subprocess.py:106} INFO - [0m13:03:18  Using profiles dir at /mnt/c/Users/psara/.dbt
[2025-01-22T13:03:18.445+0000] {subprocess.py:106} INFO - [0m13:03:18  Using profiles.yml file at /mnt/c/Users/psara/.dbt/profiles.yml
[2025-01-22T13:03:18.447+0000] {subprocess.py:106} INFO - [0m13:03:18  Using dbt_project.yml file at /mnt/c/Users/psara/shrovandbtsnowflake/dbt_project.yml
[2025-01-22T13:03:18.456+0000] {subprocess.py:106} INFO - [0m13:03:18  adapter type: snowflake
[2025-01-22T13:03:18.457+0000] {subprocess.py:106} INFO - [0m13:03:18  adapter version: 1.9.0
[2025-01-22T13:03:18.559+0000] {subprocess.py:106} INFO - [0m13:03:18  Configuration:
[2025-01-22T13:03:18.561+0000] {subprocess.py:106} INFO - [0m13:03:18    profiles.yml file [[32mOK found and valid[0m]
[2025-01-22T13:03:18.562+0000] {subprocess.py:106} INFO - [0m13:03:18    dbt_project.yml file [[32mOK found and valid[0m]
[2025-01-22T13:03:18.564+0000] {subprocess.py:106} INFO - [0m13:03:18  Required dependencies:
[2025-01-22T13:03:18.574+0000] {subprocess.py:106} INFO - [0m13:03:18   - git [[32mOK found[0m]
[2025-01-22T13:03:18.576+0000] {subprocess.py:106} INFO - 
[2025-01-22T13:03:18.578+0000] {subprocess.py:106} INFO - [0m13:03:18  Connection:
[2025-01-22T13:03:18.579+0000] {subprocess.py:106} INFO - [0m13:03:18    account: PUBFORT-NI17152
[2025-01-22T13:03:18.580+0000] {subprocess.py:106} INFO - [0m13:03:18    user: shrovan
[2025-01-22T13:03:18.581+0000] {subprocess.py:106} INFO - [0m13:03:18    database: YEAR2025
[2025-01-22T13:03:18.582+0000] {subprocess.py:106} INFO - [0m13:03:18    warehouse: COMPUTE_WH
[2025-01-22T13:03:18.583+0000] {subprocess.py:106} INFO - [0m13:03:18    role: ACCOUNTADMIN
[2025-01-22T13:03:18.583+0000] {subprocess.py:106} INFO - [0m13:03:18    schema: JAN
[2025-01-22T13:03:18.584+0000] {subprocess.py:106} INFO - [0m13:03:18    authenticator: None
[2025-01-22T13:03:18.585+0000] {subprocess.py:106} INFO - [0m13:03:18    oauth_client_id: None
[2025-01-22T13:03:18.586+0000] {subprocess.py:106} INFO - [0m13:03:18    query_tag: None
[2025-01-22T13:03:18.586+0000] {subprocess.py:106} INFO - [0m13:03:18    client_session_keep_alive: False
[2025-01-22T13:03:18.587+0000] {subprocess.py:106} INFO - [0m13:03:18    host: None
[2025-01-22T13:03:18.588+0000] {subprocess.py:106} INFO - [0m13:03:18    port: None
[2025-01-22T13:03:18.589+0000] {subprocess.py:106} INFO - [0m13:03:18    proxy_host: None
[2025-01-22T13:03:18.589+0000] {subprocess.py:106} INFO - [0m13:03:18    proxy_port: None
[2025-01-22T13:03:18.590+0000] {subprocess.py:106} INFO - [0m13:03:18    protocol: None
[2025-01-22T13:03:18.591+0000] {subprocess.py:106} INFO - [0m13:03:18    connect_retries: 1
[2025-01-22T13:03:18.592+0000] {subprocess.py:106} INFO - [0m13:03:18    connect_timeout: None
[2025-01-22T13:03:18.593+0000] {subprocess.py:106} INFO - [0m13:03:18    retry_on_database_errors: False
[2025-01-22T13:03:18.594+0000] {subprocess.py:106} INFO - [0m13:03:18    retry_all: False
[2025-01-22T13:03:18.594+0000] {subprocess.py:106} INFO - [0m13:03:18    insecure_mode: False
[2025-01-22T13:03:18.595+0000] {subprocess.py:106} INFO - [0m13:03:18    reuse_connections: True
[2025-01-22T13:03:18.596+0000] {subprocess.py:106} INFO - [0m13:03:18  Registered adapter: snowflake=1.9.0
[2025-01-22T13:03:30.089+0000] {subprocess.py:106} INFO - [0m13:03:30    Connection test: [[32mOK connection ok[0m]
[2025-01-22T13:03:30.092+0000] {subprocess.py:106} INFO - 
[2025-01-22T13:03:30.093+0000] {subprocess.py:106} INFO - [0m13:03:30  [32mAll checks passed![0m
[2025-01-22T13:03:31.796+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-22T13:03:31.824+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T13:03:31.826+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=airflow_dbt_snowflake1, task_id=dbt_tasks.dbt-debug, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T130303, end_date=20250122T130331
[2025-01-22T13:03:31.863+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-22T13:03:31.864+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-22T13:03:31.866+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake1 queued_at:2025-01-22 13:02:37.339065+00:00
[2025-01-22T13:03:31.868+0000] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-3U4JI4R2. operator:BashOperator
[2025-01-22T13:03:31.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T13:03:31.928+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T13:03:31.954+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
