[2025-01-22T13:35:27.651+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T13:35:27.662+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_dbt_snowflake3.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T13:35:27.669+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_dbt_snowflake3.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-22T13:35:27.671+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-01-22T13:35:27.713+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_tasks.dbt-debug> on 2025-01-21 00:00:00+00:00
[2025-01-22T13:35:27.717+0000] {standard_task_runner.py:72} INFO - Started process 110412 to run task
[2025-01-22T13:35:27.720+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'airflow_dbt_snowflake3', 'dbt_tasks.dbt-debug', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflake.py', '--cfg-path', '/tmp/tmpcpljgj2n']
[2025-01-22T13:35:27.722+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask dbt_tasks.dbt-debug
[2025-01-22T13:35:27.790+0000] {task_command.py:467} INFO - Running <TaskInstance: airflow_dbt_snowflake3.dbt_tasks.dbt-debug scheduled__2025-01-21T00:00:00+00:00 [running]> on host LAPTOP-3U4JI4R2.
[2025-01-22T13:35:27.886+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='airflow_dbt_snowflake3' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt-debug' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-22T13:35:27.888+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-22T13:35:27.890+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-22T13:35:27.891+0000] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt-debug state:running start_date:2025-01-22 13:35:27.664166+00:00
[2025-01-22T13:35:27.891+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake3 and current dag run status:running
[2025-01-22T13:35:27.892+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T13:35:27.894+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-22T13:35:27.896+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /mnt/c/Users/psara/.dbt --project-dir /mnt/c/Users/psara/shrovandbtsnowflake']
[2025-01-22T13:35:27.904+0000] {subprocess.py:86} INFO - Output:
[2025-01-22T13:35:38.796+0000] {subprocess.py:93} INFO - [0m13:35:38  Running with dbt=1.8.8
[2025-01-22T13:35:39.005+0000] {subprocess.py:93} INFO - [0m13:35:39  dbt version: 1.8.8
[2025-01-22T13:35:39.006+0000] {subprocess.py:93} INFO - [0m13:35:39  python version: 3.12.3
[2025-01-22T13:35:39.008+0000] {subprocess.py:93} INFO - [0m13:35:39  python path: /mnt/c/Users/psara/shrovandbtairflow/airflow_venv/bin/python3
[2025-01-22T13:35:39.009+0000] {subprocess.py:93} INFO - [0m13:35:39  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
[2025-01-22T13:35:44.014+0000] {subprocess.py:93} INFO - [0m13:35:44  Using profiles dir at /mnt/c/Users/psara/.dbt
[2025-01-22T13:35:44.016+0000] {subprocess.py:93} INFO - [0m13:35:44  Using profiles.yml file at /mnt/c/Users/psara/.dbt/profiles.yml
[2025-01-22T13:35:44.018+0000] {subprocess.py:93} INFO - [0m13:35:44  Using dbt_project.yml file at /mnt/c/Users/psara/shrovandbtsnowflake/dbt_project.yml
[2025-01-22T13:35:44.033+0000] {subprocess.py:93} INFO - [0m13:35:44  adapter type: snowflake
[2025-01-22T13:35:44.035+0000] {subprocess.py:93} INFO - [0m13:35:44  adapter version: 1.8.4
[2025-01-22T13:35:44.151+0000] {subprocess.py:93} INFO - [0m13:35:44  Configuration:
[2025-01-22T13:35:44.152+0000] {subprocess.py:93} INFO - [0m13:35:44    profiles.yml file [[32mOK found and valid[0m]
[2025-01-22T13:35:44.154+0000] {subprocess.py:93} INFO - [0m13:35:44    dbt_project.yml file [[32mOK found and valid[0m]
[2025-01-22T13:35:44.155+0000] {subprocess.py:93} INFO - [0m13:35:44  Required dependencies:
[2025-01-22T13:35:44.164+0000] {subprocess.py:93} INFO - [0m13:35:44   - git [[32mOK found[0m]
[2025-01-22T13:35:44.165+0000] {subprocess.py:93} INFO - 
[2025-01-22T13:35:44.166+0000] {subprocess.py:93} INFO - [0m13:35:44  Connection:
[2025-01-22T13:35:44.167+0000] {subprocess.py:93} INFO - [0m13:35:44    account: PUBFORT-NI17152
[2025-01-22T13:35:44.168+0000] {subprocess.py:93} INFO - [0m13:35:44    user: shrovan
[2025-01-22T13:35:44.168+0000] {subprocess.py:93} INFO - [0m13:35:44    database: YEAR2025
[2025-01-22T13:35:44.169+0000] {subprocess.py:93} INFO - [0m13:35:44    warehouse: COMPUTE_WH
[2025-01-22T13:35:44.170+0000] {subprocess.py:93} INFO - [0m13:35:44    role: ACCOUNTADMIN
[2025-01-22T13:35:44.170+0000] {subprocess.py:93} INFO - [0m13:35:44    schema: JAN
[2025-01-22T13:35:44.171+0000] {subprocess.py:93} INFO - [0m13:35:44    authenticator: None
[2025-01-22T13:35:44.172+0000] {subprocess.py:93} INFO - [0m13:35:44    oauth_client_id: None
[2025-01-22T13:35:44.173+0000] {subprocess.py:93} INFO - [0m13:35:44    query_tag: None
[2025-01-22T13:35:44.173+0000] {subprocess.py:93} INFO - [0m13:35:44    client_session_keep_alive: False
[2025-01-22T13:35:44.174+0000] {subprocess.py:93} INFO - [0m13:35:44    host: None
[2025-01-22T13:35:44.175+0000] {subprocess.py:93} INFO - [0m13:35:44    port: None
[2025-01-22T13:35:44.176+0000] {subprocess.py:93} INFO - [0m13:35:44    proxy_host: None
[2025-01-22T13:35:44.176+0000] {subprocess.py:93} INFO - [0m13:35:44    proxy_port: None
[2025-01-22T13:35:44.178+0000] {subprocess.py:93} INFO - [0m13:35:44    protocol: None
[2025-01-22T13:35:44.179+0000] {subprocess.py:93} INFO - [0m13:35:44    connect_retries: 1
[2025-01-22T13:35:44.179+0000] {subprocess.py:93} INFO - [0m13:35:44    connect_timeout: None
[2025-01-22T13:35:44.180+0000] {subprocess.py:93} INFO - [0m13:35:44    retry_on_database_errors: False
[2025-01-22T13:35:44.181+0000] {subprocess.py:93} INFO - [0m13:35:44    retry_all: False
[2025-01-22T13:35:44.182+0000] {subprocess.py:93} INFO - [0m13:35:44    insecure_mode: False
[2025-01-22T13:35:44.183+0000] {subprocess.py:93} INFO - [0m13:35:44    reuse_connections: None
[2025-01-22T13:35:44.185+0000] {subprocess.py:93} INFO - [0m13:35:44  Registered adapter: snowflake=1.8.4
[2025-01-22T13:35:45.650+0000] {subprocess.py:93} INFO - [0m13:35:45    Connection test: [[32mOK connection ok[0m]
[2025-01-22T13:35:45.652+0000] {subprocess.py:93} INFO - 
[2025-01-22T13:35:45.653+0000] {subprocess.py:93} INFO - [0m13:35:45  [32mAll checks passed![0m
[2025-01-22T13:35:47.400+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-22T13:35:47.438+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T13:35:47.439+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=airflow_dbt_snowflake3, task_id=dbt_tasks.dbt-debug, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250122T133527, end_date=20250122T133547
[2025-01-22T13:35:47.465+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-22T13:35:47.466+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-22T13:35:47.468+0000] {logging_mixin.py:190} INFO - Dag name:airflow_dbt_snowflake3 queued_at:2025-01-22 13:35:05.811929+00:00
[2025-01-22T13:35:47.469+0000] {logging_mixin.py:190} INFO - Task hostname:LAPTOP-3U4JI4R2. operator:BashOperator
[2025-01-22T13:35:47.485+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T13:35:47.500+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T13:35:47.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
